export const SET_TITLE = 'SET_TITLE'

export const SET_SOURCE_ADDRESS = 'SET_SOURCE_ADDRESS'
export const SET_DESTINATION_ADDRESS = 'SET_DESTINATION_ADDRESS'
export const SET_TRAVEL_ROUTES = 'SET_TRAVEL_ROUTES'

export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const SET_USER_ID = 'SET_USER_ID'

export const SET_UNIVERSITIES = 'SET_UNIVERSITIES'
export const SET_LOCATION_SUGGESTIONS = 'SET_LOCATION_SUGGESTIONS'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'

export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU'
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU'

export const GET_LECTURE_DETAILS = 'GET_LECTURE_DETAILS'
export const SET_LECTURE_DETAILS = 'SET_LECTURE_DETAILS'

export const SET_LECTURE = 'SET_LECTURE'

export const SET_DATE = 'SET_DATE'
export const SET_TIME = 'SET_TIME'